# Generated by Django 5.1.4 on 2025-04-21 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_auto_trade_seconds_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionViewSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='구독 시작일')),
                ('expires_at', models.DateTimeField(verbose_name='구독 만료일')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구독자')),
                ('target_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='구독 대상 트레이더')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyPageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='구독 시작일')),
                ('expires_at', models.DateTimeField(verbose_name='구독 만료일')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구독자')),
            ],
            options={
                'verbose_name': '전략 페이지 구독',
                'verbose_name_plural': '전략 페이지 구독 목록',
                'ordering': ['-expires_at'],
            },
        ),
    ]
